##Notes
#Docker hostname is docker0
#Client access (user authentication) is client.fqdn
#Admin access (configuration and not exposed to web) is admin.fqdn
#A Reverse proxy must be configured to encrypt traffic for client access. linuxserver/swag works well.
#See https://github.com/NeillCC/Docker-Compose/blob/main/resources/keycloak-reverseProxy-nginx.server for example config
#No other options MUST be changed
services:
  keycloak-mysql:
      image: mysql
      container_name: keycloak-mysql
      restart: unless-stopped
      volumes: 
        - /docker/keycloak/volumes/mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: SQLpassw0rd
        MYSQL_ROOT_PASSWORD: toor
  keycloak:
      image: quay.io/keycloak/keycloak #Official image
      container_name: keycloak
      restart: unless-stopped
      environment:
        KC_DB: "mysql" #h2-mem, h2-file, mariadb, mysql. Defaults to h2 (local file-based)
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: SQLpassw0rd
        KC_DB_URL: "jdbc:mysql://keycloak-mysql:3306/keycloak" #SQL connection string. jdbc:mysql://sqlHost:port/dbName
        KC_HOSTNAME_PORT: "8080" #must be defined or admin console will spin
        KC_HTTP_RELATIVE_PATH: "/auth" # sets global relative path
        KC_HOSTNAME_PATH: "/auth" # sets cient access path
        KC_HOSTNAME_URL: "https://client.fqdn/auth" #Auth access https://client.fqdn/auth #NOTE Path is relative to the browser. Example: https://keycloak.public.com/auth
        KC_HOSTNAME_ADMIN_URL: "http://server.fqdn:8081/auth" #Path to access admin console relative to the browser. Keycloak will append /admin. Example: http://docker:8080/auth
        #KEYCLOAK_ADMIN: admin #uncomment until sql is connected and new user setup
        #KEYCLOAK_ADMIN_PASSWORD: admin #same as above
        KC_HOSTNAME_STRICT: "false" #needed for reverse proxy over http
        KC_HOSTNAME_STRICT_BACKCHANNEL: "false" #encrypt some traffic including sql
        KC_HOSTNAME_STRICT_HTTPS: "false" #needed for reverse proxy
        KC_HTTP_ENABLED: "true" # enable listening on http. disabled by default
        KC_PROXY: "edge" #edge assumes you have a reverse proxy sitting infront of keycloak and that your firewall rules restrict traffic aside from that proxy.
        KC_METRICS_ENABLED: "true"
        KC_HEALTH_ENABLED: "true" #Health endpoints /health
      command:
        - start
        #- --optimized #Only supports h2 database
        #- start-dev #run with no security. useful for setup
      ports:
        - 8081:8080 #HTTP. 8080 was already in use.
        # - 8443:8443 #HTTPS
      depends_on:
        - keycloak-mysql
